# Site specific settings
title: "Kitabisa Security"
name: "Kitabisa Security"
keywords: "Kitabisa Responsible Disclosure"
baseurl: ""
url: "https://security.kitabisa.com"
description: "Kitabisa.com welcomes feedback from security researchers and the general public to help improve our security. If you believe you have discovered a vulnerability, privacy issue, exposed data, or other security issues in any of our assets, we want to hear from you. This policy outlines steps for reporting vulnerabilities to us, what we expect, what you can expect from us."
cover: "/assets/img/cover.jpg"
fanpage_id: ""

announcement: |-
  -----BEGIN PGP SIGNED MESSAGE-----
  Hash: SHA512

  Dear valued researchers,

  Starting from 26th July 2024, we will be taking a
  break and will not be accepting any new
  submissions during this period.

  We deeply appreciate your understanding and
  patience during this uncertain time. We look
  forward to resuming our work and engaging with
  your valuable submissions as soon as we are able.

  Thanks for your understanding and ongoing support!

  Best,
  dw1
  -----BEGIN PGP SIGNATURE-----

  iQIzBAEBCgAdFiEEDmLnOJC65PyD9kOJvZx+0YqeUHgFAmaXPk
  8ACgkQvZx+0YqeUHhrEg//ePRj3oNY6+CUwiff2rfiuH0JRDy/
  qT876L6tjeadF/j59SpZyqSVfH+cDTuMigQ/r1MYBnmcCo0oLZ
  Q13R4CcQG+eXDwe6yfttcZgARkpVQ8IhuL6v3NWqo0qP0uvC2M
  bOr+WpXcfPgFS3NE+/djFPjgoSMhY9vmDezJ81H1+UKtNWVyHy
  U3mA2vYOKUDkSOS7ngUqdB8Q7lGOkiEUWudpxwj83ZxcjXpBnh
  LQqzfB5kVsSNCsCgVWaPAAqbE34j1qJEF/ToTrMyaVTopHjnhu
  JT2k3p69b+U5qtk1/+1faTurFKqhqIJhWi3LN8NgHJCkRCxXqM
  S6wBeoKx15tFaYO1zibnZckCdirT0JUXtZRg2KUWHqA4Ug7CgD
  +BE0igz76qzcXzFez+JZduDNdeH2RqdhvP9yXLnoaVK9tKL09H
  tARvsZJATUlLbRsN2FydIJXsIDhjakegjngREJ23MJ+/MQQlQt
  2+4IYmF1gQes6MLFhuB8K+K5mG5lC/zkUD4kPGCBKxeqBtfT+k
  VByR/R+O16elFaHAqldnUBbG9k2NM1Ndl6JzW2krJY0YrneYv1
  ZERJK6CIyRMXU8Uo7ZswK75njD9xpGgbPpERhxOgZgIKR7InLH
  cjf7t14B23tBbTsWjeyq9e47KMQmpLfTg7cET7sn1vcPYG/zEN
  KBig==5xKY
  -----END PGP SIGNATURE-----

# Policy settings
email: infosec@kitabisa.com
pgp_fingerprint: 0E62 E738 90BA E4FC 83F6  4389 BD9C 7ED1 8A9E 5078
scopes:
  in:
    - value: kitabisa.com
    - value: accounts.kitabisa.com
    - value: core.kitabisa.com
    - value: donasi.kitabisa.com
    - value: galangdana.kitabisa.com
    - value: galang-dana.kitabisa.com
    - value: geni.kitabisa.com
    - value: <a href="https://play.google.com/store/apps/details?id=com.kitabisa.android">Android</a>
    - value: <a href="https://apps.apple.com/id/app/kitabisa/id1458307938">iOS</a>
    - value: waf.teler.app
    - value: <a href="https://github.com/kitabisa?type=source">https://github.com/kitabisa/*</a>
  out:
    - "*.kitabisa.com"
    - blog.kitabisa.com
    - "*docs.kitabisa.com"
    - imgix.kitabisa.com
    - maintenance.kitabisa.com
    - static*.kitabisa.com
    - "*.ktbs.dev"
    - "*.ktbs.in"
    - "*.ktbs.io"
    - "*.kitabisa.cc"
    - "*.kitabisa.org"

commitments:
  - Respond to your report promptly, and work with you to understand and validate your report;
  - Strive to keep you informed about the progress of a vulnerability as it is processed;
  - Work to remediate discovered vulnerabilities in a timely manner, within our operational constraints; and
  - Extend Safe Harbor for your vulnerability research that is related to this policy.

expectations:
  - Play by the rules, including following this policy and any other relevant agreements. If there is any inconsistency between this policy and any other applicable terms, the terms of this policy will prevail;
  - Report any vulnerability you’ve discovered promptly;
  - Avoid violating the privacy of others, disrupting our systems, destroying data, and/or harming user experience;
  - Limit the duration of the fundraising campaign to <b>1 day</b> during testing;
  - Use only the <a href="#official-channels">Official Channels</a> to discuss vulnerability information with us;
  - Provide us a reasonable amount of time to resolve the issue before you disclose it publicly;
  - Perform testing only on in-scope systems, and respect systems and activities which are out-of-scope;
  - If a vulnerability provides unintended access to data; Limit the amount of data you access to the minimum required for effectively demonstrating a Proof of Concept; and cease testing and submit a report immediately if you encounter any user data during testing, such as Personally Identifiable Information (PII), Personal Healthcare Information (PHI), credit card data, or proprietary information;
  - You should only interact with test accounts you own or with explicit permission from the account holder; and
  - Do not engage in extortion.

harbors:
  - Authorized concerning any applicable anti-hacking laws, and we will not initiate or support legal action against you for accidental, good-faith violations of this policy;
  - Authorized concerning any relevant anti-circumvention laws, and we will not bring a claim against you for circumvention of technology controls;
  - Exempt from restrictions in our Terms of Service (TOS) and/or Acceptable Usage Policy (AUP) that would interfere with conducting security research, and we waive those restrictions on a limited basis; and
  - Lawful, helpful to the overall security of the Internet, and conducted in good faith.

# Site general settings
lang: "en"
lang_alternate: "id_ID"
ssl: false # It will redirect to https

# Build settings
markdown: kramdown
permalink: /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - security.txt
  - README.md
  - bounty-calc.py